version: "3.9"

services:
  app:
    build: .
    container_name: pbfranquicias_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/pbfranquicias
      - SPRING_DATA_MONGODB_DATABASE=pbfranquicias
    command: ["java", "-jar", "app.jar"]
    networks:
      - pbfranquicias_network

  mongodb:
    image: mongo:latest
    container_name: pbfranquicias_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pbfranquicias_network

volumes:
  mongo_data:

networks:
  pbfranquicias_network:
