version: "3.9"

services:
  springboot-app:
    build: .
    container_name: pbfranquicias_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/pbfranquicias
      - SPRING_DATA_MONGODB_DATABASE=pbfranquicias
    restart: always

  mongodb:
    image: mongo:latest
    container_name: pbfranquicias_mongodb
    restart: always
    ports:
      - "27023:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
